language: ruby
rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.0
  - jruby-9.0.5.0
before_script:
  - export QINIU_ACCESS_KEY=QWYn5TFQsLLU1pL5MFEmX3s5DmHdUThav9WyOWOm
  - export QINIU_SECRET_KEY=Bxckh6FA-Fbs9Yt3i3cbKVK22UPBmAOHJcL95pGz
gemfile:
  - Gemfile
  - rails3/Gemfile
